In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3, 3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1]:
ser1 = Series([0, 1], index=['A', 'B'])
ser2 = Series([2,3,4], index=['C','D','E'])
ser3 = Series([5,6], index=['F','G'])

In [2]:
pd.concat([ser1, ser2, ser3])

A    0
B    1
C    2
D    3
E    4
F    5
G    6
dtype: int64

In [6]:
pd.concat([ser1, ser2], axis=1)

0   1
A   0 NaN
B   1 NaN
C NaN   2
D NaN   3
E NaN   4

In [7]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  A    0
      B    1
cat2  C    2
      D    3
      E    4
dtype: int64

In [8]:
pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
A     0   NaN
B     1   NaN
C   NaN     2
D   NaN     3
E   NaN     4

In [9]:
dframe1 = DataFrame(np.random.randn(4, 3), columns=['X', 'Y', 'Z'])

In [12]:
dframe1

X         Y         Z
0  0.828655  0.889771  0.601435
1  1.337627  0.713949  0.069095
2 -1.472494  0.519874 -0.400869
3  1.093393 -0.911885 -0.287570

In [10]:
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [11]:
dframe2

Y         Q         X
0  0.045060 -0.983399 -0.188651
1 -0.592100 -1.242889 -0.485794
2 -0.346745 -0.697039 -0.127935

In [15]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN  0.828655  0.889771  0.601435
1       NaN  1.337627  0.713949  0.069095
2       NaN -1.472494  0.519874 -0.400869
3       NaN  1.093393 -0.911885 -0.287570
0 -0.983399 -0.188651  0.045060       NaN
1 -1.242889 -0.485794 -0.592100       NaN
2 -0.697039 -0.127935 -0.346745       NaN

In [19]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.469907 -2.642158  0.515023
1       NaN  1.219904  0.788713 -1.605867
2       NaN -1.651907 -1.129780 -0.568462
3       NaN -0.019375 -0.566035 -0.792809
4 -0.910389 -0.971974  0.818089       NaN
5 -0.872311 -1.381476 -0.087843       NaN
6 -0.828655  0.191934 -0.040975       NaN

In [14]:
pd.concat([dframe1, dframe2], axis=1)

X         Y         Z         Y         Q         X
0  0.828655  0.889771  0.601435  0.045060 -0.983399 -0.188651
1  1.337627  0.713949  0.069095 -0.592100 -1.242889 -0.485794
2 -1.472494  0.519874 -0.400869 -0.346745 -0.697039 -0.127935
3  1.093393 -0.911885 -0.287570       NaN       NaN       NaN

In [16]:
pd.concat({'level1': dframe1, 'level2': dframe2}, axis=1)

level1                        level2                    
          X         Y         Z         Y         Q         X
0  0.828655  0.889771  0.601435  0.045060 -0.983399 -0.188651
1  1.337627  0.713949  0.069095 -0.592100 -1.242889 -0.485794
2 -1.472494  0.519874 -0.400869 -0.346745 -0.697039 -0.127935
3  1.093393 -0.911885 -0.287570       NaN       NaN       NaN