In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-1.36928623, -0.71335483,  0.82210594,  0.11898792, -0.85528647,
        0.43392785, -0.92987238, -1.99761107, -1.32562322,  0.95471266])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-1.66869524,  1.87352532,  0.53954535,  0.66651476, -0.22566122,
       -1.8034253 ,  0.77399542,  0.8681652 ,  0.01561832, -1.28207876])

In [10]:
np.add(A, B)

array([-3.03798147,  1.16017049,  1.36165129,  0.78550268, -1.08094768,
       -1.36949745, -0.15587696, -1.12944587, -1.3100049 , -0.3273661 ])

In [11]:
np.maximum(A, B)

array([-1.36928623,  1.87352532,  0.82210594,  0.66651476, -0.22566122,
        0.43392785,  0.77399542,  0.8681652 ,  0.01561832,  0.95471266])